apiVersion: v1
name: tarian-cluster-agent
version: 0.0.13
appVersion: 0.0.13
description: Anti-Virus for K8s. Protect your Applications running on Kubernetes from malicious attacks with pre-registered source code, runtime processes monitoring, analytics, alerting and also sharing detections with community. Maybe save from Ransomware.
keywords:
- security
- microservices
- containers
- anti-virus
- antivirus
- anti-viruses
- cloud-native
- cloudnative
- security-hardening
- pods
- security-tools
- devsecops
- runtime-security
- kubernetes
- tarian
- antivirus-software
- kube-tarian
home: https://github.com/kube-tarian/tarian
sources:
- https://github.com/kube-tarian/tarian
maintainers:
- name: devopstoday11
- name: andylibrian
